"""Re-run this exact bundle. Generated by TheConstruct."""
from theconstruct import create_session_bundle

URL = 'https://youtube.com/shorts/Rohm7oZnZDw?si=jtHqrrGyeHWT7-n9'

if __name__ == "__main__":
    create_session_bundle(URL)
