"""Re-run this exact bundle. Generated by TheConstruct."""
from theconstruct import create_session_bundle

URL = 'https://www.youtube.com/shorts/r6F3Mj3w8eA'

if __name__ == "__main__":
    create_session_bundle(URL)
